name: Deploy .NET App

on:
  push:
    branches:
      - master  # Ou a branch desejada

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalar .NET SDK
        run: |
          curl -sSL https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh | bash /dev/stdin --version 9.0.201
          export PATH=$PATH:/opt/render/.dotnet
          /opt/render/.dotnet/dotnet --version

      - name: Restaurar dependências
        run: /opt/render/.dotnet/dotnet restore

      - name: Compilar projeto
        run: /opt/render/.dotnet/dotnet build -c Release

      - name: Publicar projeto
        run: /opt/render/.dotnet/dotnet publish /opt/render/project/src/ivorya-back.csproj -c Release -o /opt/render/project/src/out

      - name: Executar a aplicação
        run: /opt/render/.dotnet/dotnet /opt/render/project/src/out/ivorya-back.dll
