name: Deploy .NET App to GitHub Pages

on:
  push:
    branches:
      - main  # Ou a branch que você deseja implantar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v2

      # Passo 2: Instalar o .NET SDK
      - name: Instalar .NET SDK
        run: |
          curl -sSL https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh | bash /dev/stdin --version 9.0.201
          export PATH=$PATH:/home/runner/.dotnet  # Atualizando o caminho do .NET
          /home/runner/.dotnet/dotnet --version  # Verificando a versão do .NET

      # Passo 3: Restaurar dependências
      - name: Restaurar dependências
        run: /home/runner/.dotnet/dotnet restore

      # Passo 4: Compilar o projeto
      - name: Compilar projeto
        run: /home/runner/.dotnet/dotnet build -c Release

      # Passo 5: Publicar o projeto
      - name: Publicar projeto
        run: /home/runner/.dotnet/dotnet publish -c Release -o out

      # Passo 6: Fazer o deploy no GitHub Pages
      - name: Deploy no GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.1.2
        with:
          folder: out  # Caminho onde o aplicativo foi publicado
          branch: gh-pages  # Branch para onde o conteúdo será enviado
          clean: true  # Limpar o diretório de publicação
          token: ${{ secrets.GITHUB_TOKEN }}  # Token de acesso ao repositório
