name: Build and Deploy Dockerized .NET API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t ivorya-back .

      - name: Push Docker image to Docker Hub (Optional)
        run: docker push <your-dockerhub-username>/ivorya-back:latest

      - name: Deploy to Heroku (Optional, if you're using Heroku)
        uses: akshnz/heroku-docker-deploy-action@v1
        with:
          app_name: <heroku-app-name>
          api_key: ${{ secrets.HEROKU_API_KEY }}
