name: Deploy .NET Core to Vercel

on:
  push:
    branches:
      - main  # Ou a branch que você deseja

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout do código
    - name: Checkout repository
      uses: actions/checkout@v2
    
    # 2. Instalar .NET SDK (assumindo que você queira a versão 9.0.201)
    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.201'

    # 3. Restaurar dependências
    - name: Restore dependencies
      run: dotnet restore

    # 4. Build do projeto
    - name: Build project
      run: dotnet build -c Release -o /app/build

    # 5. Publicar o projeto
    - name: Publish project
      run: dotnet publish -c Release -o /app/publish

    # 6. Deploy para o Vercel
    - name: Deploy to Vercel
      run: |
        npm install -g vercel
        vercel --prod --confirm
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
